[tox]
envlist=
     py314

[testenv]
deps =
     pytest
     pytest-sugar
commands =
     pip install -e .
     py.test tellsticknet

[pytest]
addopts=
     --doctest-modules

[testenv:lint]
deps =
     ruff
commands =
     ruff --version
     ruff check tellsticknet pyproject.toml
     ruff format --check tellsticknet
